site_name: Epic Fight Wiki
repo_url: https://github.com/Yesssssman/epicfightmod
copyright: GNU GENERAL PUBLIC LICENSE
plugins:
  - social:
  - search:
      lang:
        - en
        - pl
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
       - build: true
         default: true
         locale: en
         name: English
       - build: true
         default: false
         locale: pt
         name: Português
         nav_translations:
            Armor: Armadura
            Guides: Guias
            Misc: Diversos
       - build: true
         default: false
         locale: es
         name: Español
         nav_translations:
            Armor: Armadura
            Guides: Guías
            Misc: Miscelánea
       - build: true
         default: false
         locale: ru
         name: Русский
         nav_translations:
            Armor: Броня
            Guides: Руководства
            Misc: Разное
       - build: true
         default: false
         locale: pl
         name: Polski
         nav_translations:
            Armor: Zbroja
            Guides: Poradnik
            Misc: Różne
       - build: true
         default: false
         locale: ja
         name: 日本語
         nav_translations:
            Armor: アーマー
            Guides: ガイド
            Misc: その他
       - build: true
         default: false
         locale: uk
         name: українська
         nav_translations:
            Armor: броня
            Guides: напрямні
            Misc: Різне
       - build: true
         default: false
         locale: zh
         name: 中文
         nav_translations:
            Armor: 盔甲
            Guides: 指南
            Misc: 杂项
       - build: true
         default: false
         locale: ko
         name: 한국어
         nav_translations:
            Armor: 방어구
            Guides: 가이드
            Misc: 기타
       - build: true
         default: false
         locale: hr
         name: Hrvatski
         nav_translations:
            Armor: Oklop
            Guides: Vodiči
            Misc: Razno
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: MetalKnight56/EpicFight-Docs
      branch: main
theme:
  name: material
  custom_dir: overrides
  font: false
  favicon: assets/icon.png
  logo: assets/logo.png
  palette:
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: clear_day
        name: Switch to light mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: clear_night
        name: Switch to dark mode
  features:
    - toc.integrate
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tracking
    - search.sticky
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
extra:
  social:
    - icon: github 
      link: https://github.com/Yesssssman/epicfightmod
      name: GitHub
    - icon: curseforge
      link: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod
      name: CurseForge
    - icon: modrinth
      link: https://modrinth.com/mod/epic-fight
      name: Modrinth
    - icon: discord
      link: https://discord.com/invite/NbAJwj8RHg
      name: Discord
    - icon: youtube
      link: https://www.youtube.com/@yesman4100
      name: YouTube
  analytics: 
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie Consent
    description: >- 
      We at the Epic Fight Team collect cookies in order to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. By giving your consent, you're helping us improve our documentation and giving us an important feedback on each page here :)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
