site_name: My Docs
repo_url: https://github.com/Yesssssman/epicfightmod
plugins:
  - search:
      lang:
        - en
        - pl
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: false
        pt:
          name: Português
          build: true
        es:
          name: Español
          build: true
        ru:
          name: Русский
          build: true
        pl:
          name: Polski
          build: true
        ja:
          name: 日本語
          build: true
        uk:
          name: українська
          build: true
        zh:
          name: 中文
          build: true
        ko:
          name: 한국어
          build: true
          
      nav_translations:
        pt:
          Armor: Armadura
          Guides: Guias
        es:
          Armor: Armadura
          Guides: Guías
        ru:
          Armor: Броня  
          Guides: Руководства
        pl:
          Armor: Zbroja
          Guides: Poradnik
        ja:
          Armor: アーマー
          Guides: ガイド
        uk:
          Armor: броня
          Guides: напрямні
        zh:
          Armor: 盔甲
          Guides: 指南
        ko:
          Armor: 방어구
          Guides: 가이드
theme:
  name: material
  font: false
  palette:
    primary: red
  features:
    - header.autohide
