site_name: Epic Fight Wiki
repo_url: https://github.com/Yesssssman/epicfightmod
copyright: GNU GENERAL PUBLIC LICENSE
plugins:
  - social:
  - search:
      lang:
        - en
        - pl
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: false
        pt:
          name: Português
          build: true
        es:
          name: Español
          build: true
        ru:
          name: Русский
          build: true
        pl:
          name: Polski
          build: true
        ja:
          name: 日本語
          build: true
        uk:
          name: українська
          build: true
        zh:
          name: 中文
          build: true
        ko:
          name: 한국어
          build: true
        hr:
          name: Hrvatski
          build: true
          
      nav_translations:
        pt:
          Armor: Armadura
          Guides: Guias
          Misc: Diversos
        es:
          Armor: Armadura
          Guides: Guías
          Misc: Miscelánea
        ru:
          Armor: Броня  
          Guides: Руководства
          Misc: Разное
        pl:
          Armor: Zbroja
          Guides: Poradnik
          Misc: Różne
        ja:
          Armor: アーマー
          Guides: ガイド
          Misc: その他
        uk:
          Armor: броня
          Guides: напрямні
          Misc: Різне
        zh:
          Armor: 盔甲
          Guides: 指南
          Misc: 杂项
        ko:
          Armor: 방어구
          Guides: 가이드
          Misc: 기타
        hr:
          Armor: Oklop
          Guides: Vodiči
          Misc: Razno
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: MetalKnight56/EpicFight-Docs
      branch: main
      enabled: !ENV [CI, false]
theme:
  name: material
  custom_dir: overrides
  font: false
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tracking
    - search.sticky
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
extra:
  social:
    - icon: github 
      link: https://github.com/Yesssssman/epicfightmod
      name: GitHub
    - icon: curseforge
      link: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod
      name: CurseForge
    - icon: modrinth
      link: https://modrinth.com/mod/epic-fight
      name: Modrinth
    - icon: discord
      link: https://discord.com/invite/NbAJwj8RHg
      name: Discord
    - icon: youtube
      link: https://www.youtube.com/@yesman4100
      name: YouTube
extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-EN680XXN1W
  - |
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-EN680XXN1W');