site_name: Epic Fight Wiki
repo_url: https://github.com/Yesssssman/epicfightmod
plugins:
  - search:
      lang:
        - en
        - pl
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: false
        pt:
          name: Português
          build: true
        es:
          name: Español
          build: true
        ru:
          name: Русский
          build: true
        pl:
          name: Polski
          build: true
        ja:
          name: 日本語
          build: true
        uk:
          name: українська
          build: true
        zh:
          name: 中文
          build: true
        ko:
          name: 한국어
          build: true
        hr:
          name: Hrvatski
          build: true
          
      nav_translations:
        pt:
          Armor: Armadura
          Guides: Guias
          Misc: Diversos
        es:
          Armor: Armadura
          Guides: Guías
          Misc: Miscelánea
        ru:
          Armor: Броня  
          Guides: Руководства
          Misc: Разное
        pl:
          Armor: Zbroja
          Guides: Poradnik
          Misc: Różne
        ja:
          Armor: アーマー
          Guides: ガイド
          Misc: その他
        uk:
          Armor: броня
          Guides: напрямні
          Misc: Різне
        zh:
          Armor: 盔甲
          Guides: 指南
          Misc: 杂项
        ko:
          Armor: 방어구
          Guides: 가이드
          Misc: 기타
        hr:
          Armor: Oklop
          Guides: Vodiči
          Misc: Razno
theme:
  name: material
  font: false
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
